import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Navigation/header";
import {MenuContextProvider, useMenuContext} from "@/context/MenuContext";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
      <html lang="en">
      <body>
      <MenuContextProvider>
      <Header />
          {children}
      </MenuContextProvider>
      </body>
</html>
  )
}
